name: Deploy to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 -d > hana.pem
          chmod 600 hana.pem

      - name: Copy files to EC2
        run: |
          rsync -avz -e "ssh -i hana.pem -o StrictHostKeyChecking=no" ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/backend-hana

      - name: SSH and restart server
        run: |
          ssh -i hana.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/${{ secrets.EC2_USER }}/backend-hana
            npm install
            pm2 restart index.js || pm2 start index.js
          EOF